class TestException ( BaseException ):

    def __init__( self, err ):
            self.err = err
            pass
